// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Projects → All Projects*
 */
export interface ProjectsDocumentDataAllProjectsItem {
  /**
   * Name field in *Projects → All Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.all_projects[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Desciption field in *Projects → All Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.all_projects[].desciption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  desciption: prismic.KeyTextField;

  /**
   * Image field in *Projects → All Projects*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.all_projects[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Home field in *Projects → All Projects*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: projects.all_projects[].home
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  home: prismic.BooleanField;

  /**
   * Date field in *Projects → All Projects*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.all_projects[].date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Link Live field in *Projects → All Projects*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.all_projects[].link_live
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_live: prismic.LinkField;

  /**
   * Link Github field in *Projects → All Projects*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.all_projects[].link_github
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_github: prismic.LinkField;

  /**
   * Tools field in *Projects → All Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: EX: HTML - CSS - Js - React.js
   * - **API ID Path**: projects.all_projects[].tools
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tools: prismic.KeyTextField;
}

type ProjectsDocumentDataSlicesSlice = never;

/**
 * Content for Projects documents
 */
interface ProjectsDocumentData {
  /**
   * Title Section field in *Projects*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.title_section
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title_section: prismic.TitleField;

  /**
   * Description Section field in *Projects*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.description_section
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description_section: prismic.RichTextField;

  /**
   * All Projects field in *Projects*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.all_projects[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  all_projects: prismic.GroupField<
    Simplify<ProjectsDocumentDataAllProjectsItem>
  >;

  /**
   * Slice Zone field in *Projects*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProjectsDocumentDataSlicesSlice> /**
   * Meta Description field in *Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: projects.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Projects*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: projects.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Projects document from Prismic
 *
 * - **API ID**: `projects`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectsDocumentData>,
    "projects",
    Lang
  >;

/**
 * Item in *Skills → icons*
 */
export interface SkillsDocumentDataIconsItem {
  /**
   * name field in *Skills → icons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.icons[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * svg field in *Skills → icons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.icons[].svg
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  svg: prismic.KeyTextField;
}

/**
 * Content for Skills documents
 */
interface SkillsDocumentData {
  /**
   * icons field in *Skills*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.icons[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  icons: prismic.GroupField<Simplify<SkillsDocumentDataIconsItem>>;

  /**
   * size field in *Skills*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.size
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  size: prismic.NumberField;
}

/**
 * Skills document from Prismic
 *
 * - **API ID**: `skills`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SkillsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<SkillsDocumentData>, "skills", Lang>;

export type AllDocumentTypes = ProjectsDocument | SkillsDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ProjectsDocument,
      ProjectsDocumentData,
      ProjectsDocumentDataAllProjectsItem,
      ProjectsDocumentDataSlicesSlice,
      SkillsDocument,
      SkillsDocumentData,
      SkillsDocumentDataIconsItem,
      AllDocumentTypes,
    };
  }
}
